import Head from 'next/head'
import Header from '../components/Header/Header'
import Nav from '../components/Nav/Nav'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Hulu 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* Header */}
      <Header></Header>
      {/* Nav */}
      <Nav/>
    </div>
  )
}
